development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p876b548bb194add931feae98244f669d218a445b6a5667711829b83ddb9ab909@ec2-34-204-150-189.compute-1.amazonaws.com:32379
  channel_prefix: message_me_production
